---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-proxy
  namespace: auth
spec:
  type: NodePort
  ports:
  - name: keycloak-proxy
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32004
  selector:
    name: keycloak-proxy
