---
apiVersion: v1
kind: Service
metadata:
  name: loginapp
  namespace: auth
spec:
  type: NodePort
  ports:
  - name: loginapp
    port: 5555
    protocol: TCP
    targetPort: 5555
    nodePort: 32002
  selector:
    app: loginapp
