apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: superadmins
subjects:
  - kind: Group
    name: devops
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cesreaders
  namespace: auth
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get","list","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cesdeployers
  namespace: auth
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments","statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cesreaders
  namespace: auth
subjects:
  - kind: Group
    name: system:authenticated
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: cesreaders
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cesdeployers
  namespace: auth
subjects:
  - kind: Group
    name: qa
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: dev
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: cesdeployers
  apiGroup: rbac.authorization.k8s.io
